stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: ./src
      tag: atriarch-status:v1.0.${CICD_EXECUTION_SEQUENCE}
      pushRemote: true
      registry: docker.atriarch.systems
- name: Deploy
  steps:
  - applyYamlConfig:
      path: ./service.yaml
timeout: 10
notification:
  recipients:
  - recipient: pipelineNotifications@mail.atriarch.systems
    notifier: c-56lvs:n-45qs9
  condition:
  - Failed
