apiVersion: serving.knative.dev/v1 # Current version of Knative
kind: Service
metadata:
  name: atriarch-status # The name of the app
  namespace: atriarch-status # The namespace the app will use
  labels:
    domain: atriarch
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "10"
    spec:
      containers:
        - name: atriarch-status
          image: ${CICD_IMAGE}:v1.0.${CICD_EXECUTION_SEQUENCE} # The URL to the image of the app
          livenessProbe:
            httpGet:
              path: /
          readinessProbe:
            httpGet:
              path: /
      imagePullSecrets:
      - name: atriarch-systems-docker-group
